# Generated by Django 2.2.1 on 2019-05-25 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20190525_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemoption',
            name='lunch_place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='places.LunchPlace'),
            preserve_default=False,
        ),
    ]
