# Generated by Django 2.2.1 on 2019-05-25 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_itemoption_lunch_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemoption',
            name='lunch_place',
        ),
    ]
