# Generated by Django 2.2.1 on 2019-05-25 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_itemoption_lunch_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunchplace',
            name='name',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 4', regex='^\\w{4,20}$')]),
        ),
    ]
