# Generated by Django 2.2.1 on 2019-05-25 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20190525_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='lunch_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='places.LunchPlace'),
        ),
    ]
