# Generated by Django 2.2.1 on 2019-05-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20190525_2340'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('name', 'lunch_place'), name='No duplicate dish.'),
        ),
    ]
