# Generated by Django 2.2.1 on 2019-05-25 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20190526_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='option',
            new_name='options',
        ),
    ]
