# Generated by Django 2.2.1 on 2019-05-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_auto_20190526_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='options',
            field=models.ManyToManyField(related_name='items', to='places.ItemOption'),
        ),
    ]
