# Generated by Django 2.2.1 on 2019-05-26 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_auto_20190526_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='options',
        ),
    ]
