# Generated by Django 2.2.1 on 2019-05-26 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190526_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userOrders', to='orders.Order'),
        ),
    ]
